#!/bin/bash

if [ $# = 0 ]; then

  redshift -o -t 2700:2700 -l 0.0:0.0 -g 1  
  exit 0

fi

red=2700
gamma=1


usage() { echo "Usage: $0 [-r <1000|25000>] [-g <0:1>]" 1>&2; exit 1; }

while getopts ":r:g:" o; do
    case "${o}" in
        r)
            red=${OPTARG}
            if [ $red -lt 1000 ] || [ $red -gt 25000 ]; then
              usage
            fi
            ;;
        g)
            gamma=${OPTARG}
            less_than="$(echo $gamma'<'0 | bc)"
            greater_than="$(echo $gamma'>'1 | bc)"
            if [ $less_than = 1 ] || [ $greater_than = 1 ]; then
              usage
            fi
            ;;
        *)
            usage
            ;;
    esac
done

redshift -o -t $red:$red -l 0.0:0.0 -g $gamma
